<x-app-layout title="Dashboard" header="Visão geral" :partial="$partial ?? false">
    <div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="mb-2 text-sm font-medium text-blue-600">{{ now()->format('d/m/Y') }}</p><h1 class="text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">Visão geral</h1><p class="mt-2 text-sm text-slate-500">Acompanhe a operação fiscal da sua empresa.</p></div><x-button href="{{ route('nfe.create') }}" tag="a"><x-icon name="plus" class="h-4 w-4" /> Nova NF-e</x-button></div>
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        @foreach([['Notas emitidas','0','Sem emissões ainda','blue'],['Autorizadas','0','Nenhuma nota autorizada','emerald'],['Processando','0','Nenhuma nota em processamento','amber'],['Rejeitadas','0','Nenhuma nota rejeitada','red']] as $card)
            <div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between"><p class="text-sm font-medium text-slate-500">{{ $card[0] }}</p><span class="h-2.5 w-2.5 rounded-full bg-{{ $card[3] }}-500"></span></div><p class="mt-5 text-3xl font-bold tracking-tight text-slate-950">{{ $card[1] }}</p><p class="mt-2 text-xs text-{{ $card[3] }}-600">{{ $card[2] }}</p></div>
        @endforeach
    </div>
    <div class="mt-6 grid gap-6 xl:grid-cols-[1.35fr_1fr]"><div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><div><h2 class="font-semibold text-slate-900">Volume de emissões</h2><p class="mt-1 text-sm text-slate-500">Notas emitidas nos últimos 7 dias</p></div><span class="rounded-lg bg-slate-100 px-3 py-2 text-xs font-medium text-slate-600">Sem dados</span></div><div class="flex h-48 items-center justify-center text-sm text-slate-400">As emissões aparecerão aqui após a primeira NF-e.</div></div><div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="font-semibold text-slate-900">Ações rápidas</h2><div class="mt-5 space-y-3"><a href="{{ route('nfe.create') }}" class="flex items-center gap-4 rounded-xl border border-slate-200 p-4 transition hover:border-blue-200 hover:bg-blue-50/50"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><x-icon name="plus" class="h-5 w-5" /></span><span><span class="block text-sm font-semibold text-slate-800">Emitir nova NF-e</span><span class="mt-1 block text-xs text-slate-500">Preencha os dados da operação</span></span><span class="ml-auto text-slate-400">→</span></a><a href="{{ route('nfe.index') }}" class="flex items-center gap-4 rounded-xl border border-slate-200 p-4 transition hover:border-blue-200 hover:bg-blue-50/50"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100 text-slate-600"><x-icon name="receipt" class="h-5 w-5" /></span><span><span class="block text-sm font-semibold text-slate-800">Consultar histórico</span><span class="mt-1 block text-xs text-slate-500">Veja todas as notas emitidas</span></span><span class="ml-auto text-slate-400">→</span></a></div></div></div>
</x-app-layout>
